version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-server
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_LOG_LEVEL: INFO
    command: start-dev
    volumes:
      - ./keycloak-data:/opt/keycloak/data # Asigură-te că directorul ./keycloak-data este accesibil și nu ai probleme de permisiuni.
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - binge-buddies-net

networks:
  binge-buddies-net:
    driver: bridge